title: Come What May
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jayheo1106.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Jay Heo'
  last_name: 'Heo'
  cv: 'https://linkedin.com/in/jae-young-heo'
  avatar: '/images/myphoto.jpeg'
  github_username:  jayheo1106 
  email: wodudgj1106@gmail.com
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html
