title: Come What May
description: > # this means to ignore newlines until "baseurl:"
  MS statistics @TAMU
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jayheo1106.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jay Heo # add your name
author-img: jayheo.jpeg # add your photo
about-author: I am in the process of documenting the work I've done so far. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: jayheo1106 # add your Github handle
social-linkedin: "https://www.linkedin.com/in/jae-young-heo" # add your Linkedin handle
social-email: wodudgj1106@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
